### ISSUE TITLE
Build failed (Release mode)

### ISSUE THREAD

**Issue by movieator** [lotrofans/get_ip_flutter#13]
Hi, I'm trying to run my project in release mode. I get the following error message:

> FAILURE: Build failed with an exception.                                                                           
>                                                                                                                    
> * What went wrong:                                                                                                 
> Execution failed for task ':get_ip:verifyReleaseResources'.                                                        
> > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
> 
>   /Users/******/Desktop/Source/Flutter/******/build/get_ip/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.
>   /Users/******/Desktop/Source/Flutter/******/build/get_ip/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.
>   error: failed linking references. 

My flutter doctor results:

> [✓] Flutter (Channel master, v1.10.15-pre.330, on Mac OS X 10.15 19A602, locale el-GR)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.3)
> [✓] VS Code (version 1.39.2)
> [✓] Connected device (3 available)
> 
> • No issues found!

I use AndroidX migration. In debug mode, everything works fine!
Thanks!

**Comment by Ciock** [comment]
same as above

**Comment by basnetjiten** [comment]
same problem here after updating flutter to 1.12

**Comment by komekh** [comment]
same problem
`[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17134.1184], locale tr-TR)
    • Flutter version 1.12.13+hotfix.5 at C:\Program Flutter\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0`

**Comment by khashayarmotarjemi** [comment]
> Hi, I'm trying to run my project in release mode. I get the following error message:
> 
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   Execution failed for task ':get_ip:verifyReleaseResources'.
> > 
> > > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
> > 
> > 
> > /Users/******/Desktop/Source/Flutter/******/build/get_ip/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.
> > /Users/******/Desktop/Source/Flutter/******/build/get_ip/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.
> > error: failed linking references.
> 
> My flutter doctor results:
> 
> > [✓] Flutter (Channel master, v1.10.15-pre.330, on Mac OS X 10.15 19A602, locale el-GR)
> > [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> > [✓] Xcode - develop for iOS and macOS (Xcode 11.1)
> > [✓] Chrome - develop for the web
> > [✓] Android Studio (version 3.3)
> > [✓] VS Code (version 1.39.2)
> > [✓] Connected device (3 available)
> > • No issues found!
> 
> I use AndroidX migration. In debug mode, everything works fine!
> Thanks!

the error must be gone now with migration to AndroidX. test please.

**Comment by lotrofans** [comment]
Upgrade to `get_ip: ^0.4.0` which should fix this issue.
