### ISSUE TITLE
Fails to build release

### ISSUE THREAD

**Issue by jasonjcornwell** [lotrofans/get_ip_flutter#4]
My project will fail to build when I add "get_ip: 0.2.0" to the yaml file. I have many other packages which are working fine.
I am however able to build in debug mode.

Help will be appreciated.

This is my error log:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :get_ip.
     Required by:
         project :app
      > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       7.7s
Gradle task assembleRelease failed with exit code 1

Flutter Doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.17763.379], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[!] VS Code (version 1.32.3)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by lotrofans** [comment]
Hi!
Thank You for your issue report. This is very strange, I created a flutter project and added get_ip: 0.2.0 Then I built it in release mode and I'm not getting the error. I'm sorry but I can't reproduce it so I can't help. :(
