### ISSUE TITLE
External or Internal ip address ?

### ISSUE THREAD

**Issue by pascalf22** [lotrofans/get_ip_flutter#8]
Hello ! 

Thanks for this plugin ! I love it ! Easy to use.

I receive this address ip : 192.168.232.2 when i do this : 
```
String ipAddress = await GetIp.ipAddress;
    print(ipAddress);
```

It's an internal address ip ? Is it possible to get the external address ip ?

Thanks

**Comment by javib51** [comment]
Hey! I just checked it. It provides the external address ip

**Comment by pascalf22** [comment]
Thanks !! I Appreciate :)
Have a great day

**Comment by Hector1990** [comment]
I have the same problem.

**Comment by atrope** [comment]
i am getting internal IP also,  how did you solved it?
@pascalf22 @javib51

**Comment by javib51** [comment]
> i am getting internal IP also, how did you solved it?
> @pascalf22 @javib51

Are you testing it from the phone or the emulator? I tested it using the phone and it was working fine

**Comment by atrope** [comment]
Hi,
Tested on emulator and also from device.

Both of them are getting 192.xxx

**Comment by bimsina** [comment]
Did anybody find a way to get the public IP address?

**Comment by lotrofans** [comment]
Hey everyone.
The package returns the ip address your device is aware of. If you are connected to wifi you get the internal ip address. 
If you are connected to mobile data you get the external.

You can do a simple GET request to https://api.ipify.org/ to get the public/external ip address of your device. To perfom the request use following code:
`var external = await HttpRequest.getString("https://api.ipify.org");`
